# Generated by Django 2.2.6 on 2019-10-10 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emissor',
            old_name='cpnj',
            new_name='cnpj',
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='emissor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Emissor', to_field='cnpj'),
        ),
    ]
